### PR TITLE
Bug Fixes for v1.4

### LINKED ISSUE #106: [PE-D][Tester C] Quick start command doesn't seem to work as it should
Refer to attached image. The `Quick Start` section gives the example of the command `add n/Fu Yiqiao p/91234567 e/fyq@gmail.com id/A1234567E t/G10`, however performing this upon startup gives an error that the person is already in the address book. However, that doesn't appear to be the case.

Note: switching to the CS2030S address book, it is possible to add there.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: kiatkat/ped#1

### LINKED ISSUE #107: [PE-D][Tester B] Add Course: No validation for course name
There should be a validation check to only allow courses which are 
2 initial letters, 4 numbers , and 1 optional letter. 

Perhaps you could look at my team repo for how we implemented the Course validation check.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: devanshubisht/ped#2

### LINKED ISSUE #108: [PE-D][Tester B] Course Delete: Error message may not be very specific
Error message displayed mentions address book. instead you should perhaps mention course.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: devanshubisht/ped#3

### LINKED ISSUE #118: [PE-D][Tester B] Add Student: Name cannot contain certain special characters
Cannot enter - in peoples name. - can be seen in some peoples name in real life

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: devanshubisht/ped#5

### LINKED ISSUE #127: [PE-D][Tester E] Student name restriction: no numbers restriction not working
According to the user guide, STUDENT_NAME not supposed to contain numbers, but I could still create a student even when the name field consist of numbers.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: ruo-x/ped#3

### LINKED ISSUE #133: [PE-D][Tester A] Find feature description misleading
Current description for an example with multiple names goes like:

find n/Anthony Yiqiao Finds all contacts with the name “Anthony” and “Yiqiao”.

"Anthony" and "Yiqiao" gives impression that the contact's name must include both name excerpts. 

Recommend to say "find n/Anthony Yiqiao Finds all contacts with the name “Anthony” and/or “Yiqiao”."

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: awhb/ped#6

### LINKED ISSUE #139: [PE-D][Tester D] Empty reason of absence is allowed
Able to put reason of absence with no characters. Not sure if this is supposed to work.

Command used here is `mark n/Tan Liyan a/0 w/1 r/`

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: rayshawntan/ped#9

### LINKED ISSUE #140: [PE-D][Tester C] Error message for `mark` when no reason is provided is insufficiently descriptive
When no reason is provided when marking a student absent, the program throws an error as expected according to the User Guide. However, the actual error displayed to the user in the program does not actually mention this requirement, which is somewhat confusing. The user probably should not have to visit the User Guide to find out what the actual cause of the error is, as the current error message does not imply that the input is actually invalid.

See attached as an example.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: kiatkat/ped#7

### LINKED ISSUE #144: [PE-D][Tester D] Able to find name with numbers
UG mentioned not being able to find name with numbers. However, am able to do so.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: rayshawntan/ped#10

### LINKED ISSUE #152: Update PPP
Updated:
- [x] Anthony
- [x] Liyan
- [x] Zong Jin
- [x] Elgin
- [x] Yiqiao

### PR DESCRIPTION
**Pull request by anthonytamzil**
Addresses Issue #106, #107, #108, #118, #127, #133, #139, #140, #144, #152, 

Changes:
- Added `Appendix: Planned Enhancements` and UML diagrams to `DeveloperGuide.md`
- Updated `UserGuide.md` to enhance clarity, including quick start command
- Updated `anthonytamzil.md` (PPP)
- Fixed bug in `MarkAttendanceCommandParser` to check for empty strings in reason of absence
- Add validation check for numbers in `Name`

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Name.java [hunk 1]
```diff
@@ -35,6 +39,10 @@ public Name(String name) {
      * Returns true if a given string is a valid name.
      */
     public static boolean isValidName(String test) {
+        if (test.matches(NUMBER_VALIDATION_REGEX)) {
+            return false;
+        }
+
```
Comment (spatuly) [inline src/main/java/seedu/address/model/person/Name.java:45]: With this check MESSAGE_CONSTRAINTS should be changed to alphabetical characters instead of alphanumeric?

File: src/test/java/seedu/address/model/person/NameTest.java [hunk 2]
```diff
@@ -29,13 +29,14 @@ public void isValidName() {
         assertFalse(Name.isValidName(" ")); // spaces only
         assertFalse(Name.isValidName("^")); // only non-alphanumeric characters
         assertFalse(Name.isValidName("peter*")); // contains non-alphanumeric characters
```
Comment (spatuly) [inline src/test/java/seedu/address/model/person/NameTest.java]: not exactly a problem but comments could be changed to reflect the correct restrictions

**Review by spatuly — CHANGES_REQUESTED** [review]

**Comment by spatuly** [comment]
LGTM
