### PR TITLE
Bug Fixes for v1.4

### LINKED ISSUE #137: [PE-D][Tester B] List Attendance: Issue with specificity of error
Error is due to wrong prefix used and not the number being wrong.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: devanshubisht/ped#13

### PR DESCRIPTION
**Pull request by spatuly**
Addresses #132, #136, #145, #149, #156, #157, #160

Changes:
- #132: Fixed by removing traces of the incorrect usage of the word "tags" in the UI and UserGuide.md that were left from AB3
- #136, #149: Fixed by removing Clear command from TAvigator
- #145: Fixed by adding viewCommand.png 
- #156: Fixed by adding check for "r/"
- #157: Fixed by modifying ContainsTagPredicate to disallow described incorrect results
- #160: Fixed by modifying Person equality check to include attendance records such that MarkAttendanceCommand tests would work correctly
- Updated spatuly.md (PPP) 
- Updated UserGuide.md
- Updated DeveloperGuide.md on Planned Enhancement

### CODE REVIEW

File: src/main/java/seedu/address/model/predicate/ContainsTagPredicate.java [hunk 1]
```diff
@@ -22,7 +22,7 @@ public class ContainsTagPredicate extends SerializablePredicate {
      */
     public ContainsTagPredicate(Optional<Tag> tag) {
         super(person -> person.getTags().stream().anyMatch(
-                personTag -> StringUtil.containsWordIgnoreCase(personTag.getTagName(), tag.get().getTagName())));
+                personTag -> personTag.equals(tag.get())));
```
Comment (0xteet0) [inline src/main/java/seedu/address/model/predicate/ContainsTagPredicate.java:24]: Line 8 Checkstyle Error

`import seedu.address.commons.util.StringUtil;` no longer being used, resulting in unused import checkstyle error

**Review by 0xteet0 — CHANGES_REQUESTED** [review]
LGTM besides the checkstyle error

**Comment by 0xteet0** [comment]
LGTM! 👍🏻
